language: ruby
env:
  global:
    - CC_TEST_REPORTER_ID=af34ce54e1fabdb5b5efa4c552ce00d5a63da936c2b87de8d1cd51c942d2d5d8
rvm:
  - 2.5.1
  - 2.6.2
  - jruby
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT